### ISSUE TITLE
ChatKit SDK's function attributes changed, now accepts an associative $options array

### ISSUE THREAD

**Issue by mvrska** [shalvah/pusher-chatkit-laravel#2]
For example `ChatkitFactory@createClient`  needs to be updated to

```
    /**
     * Instantiate a new Chatkit client.
     *
     * @param string[] $config
     *
     * @return Chatkit
     */
    protected function createClient(array $config): Chatkit
    {
        return new Chatkit($config);
    }
```
If anyone stubles upon issues when instantiating like
`MissingArgumentException('You must provide an instance_locator');` or `MissingArgumentException('You must provide a key');`

**Comment by shalvah** [comment]
I've updated the package to match this now. Thanks!
