### ISSUE TITLE
Documentation is out of date with current pusher/chatkit SDK

### ISSUE THREAD

**Issue by liamandrewmaddison** [shalvah/pusher-chatkit-laravel#3]
Great package and thank you for your time with this package!

Currently the documentation is incorrect with the latest chakit version.

All methods accept only one array param ``$options``, which is contrary to what the documentation explains, for example:

```
$chatkitRoom = $this->chatkit->createRoom([
    'name' => 'Samuel and Jessica',
    'private' => true,
    'user_ids' => ["Jessica"],
    'creator_id' => "Samuel",
]);
```

instead of 

```
$chatkitManager->createRoom('hc', ['name' => 'Cat Lovers']);
```
Same goes for all methods

**Comment by shalvah** [comment]
Thanks @liamm95 . Fixing in a bit.
